/*
CODE GENERATED BY "github.com/wrfly/bindata" 
@2019-06-19T23:21:38+08:00

Files:
	/
	/index.html

DO NOT EDIT!
*/

package asset

import (
	"os"
	"time"
)

var _compress_bytes_0 = []byte("\x78\x9c\x01\x00\x00\xff\xff\x00\x00\x00\x01")

var _file_0 = &file{
	fileInfo: &fileInfo{
		name:  "/",
		isDir: true,
		size:  4096,
		mode:  os.FileMode(2147484157),
		mTime: time.Unix(1560955807, 0),
		cType: "",
	},
	path:  "/",
	dirP:  "/",
	sPath: "/",
	id:    0,
	cb:    _compress_bytes_0,
}

var _compress_bytes_1 = []byte("" +
	"\x78\x9c\xb2\x51\x74\xf1\x77\x0e\x89\x0c\x70\x55\xc8\x28\xc9" +
	"\xcd\xb1\xe3\xb2\xc9\x48\x4d\x4c\xb1\xe3\x52\x50\x50\x50\xb0" +
	"\x29\xc9\x2c\xc9\x49\xb5\xf3\x48\xcd\xc9\xc9\x57\x08\xcf\x2f" +
	"\xca\x49\xb1\xd1\x87\x08\x71\xd9\xe8\x43\x94\xd9\x64\x18\x22" +
	"\xcb\x2b\xda\xe8\x67\x18\x82\x65\x41\x66\x01\x02\x00\x00\xff" +
	"\xff\xf5\xfc\x1b\xf5")

var _file_1 = &file{
	fileInfo: &fileInfo{
		name:  "index.html",
		isDir: false,
		size:  91,
		mode:  os.FileMode(436),
		mTime: time.Unix(1560955867, 0),
		cType: "text/html; charset=utf-8",
	},
	path:  "/index.html",
	dirP:  "/",
	sPath: "/index.html",
	id:    1,
	cb:    _compress_bytes_1,
}

func init() {
    fs = []*file{
		_file_0, _file_1,
	}

	root = &data{
		prefix: "/",
		files:  make(map[string]*file, len(fs)),
	}
}
